import AppKit
import CryptoKit
import Foundation

// MARK: - Capture payload

/// A clipboard snapshot captured on the polling queue, safe to hand across
/// concurrency domains (Sendable).
struct ClipboardCapture: Sendable {
    enum Content: Sendable {
        case text(String)
        /// Raw PNG/TIFF bytes straight from the pasteboard.
        case imageRaw(Data)
        /// Processed image, ready to persist.
        case image(originalPNG: Data, thumbnailPNG: Data)
    }

    let content: Content
}

// MARK: - Hashing

enum ClipboardHash {
    static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}

// MARK: - Pasteboard reader

enum ClipboardReader {
    /// Pasteboard conventions (nspasteboard.org) used by password managers
    /// and sensitive-content apps. CopyNinja never collects these.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "org.nspasteboard.TransientType"
    ]

    /// Reads the current pasteboard content, or `nil` when it is empty or
    /// excluded (concealed / auto-generated / transient data).
    static func read(from pasteboard: NSPasteboard) -> ClipboardCapture? {
        let typeNames = pasteboard.types?.map(\.rawValue) ?? []
        if typeNames.contains(where: excludedTypes.contains) {
            return nil
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipboardCapture(content: .text(string))
        }

        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            return ClipboardCapture(content: .imageRaw(data))
        }

        return nil
    }
}

// MARK: - Background poller

/// Watches `NSPasteboard.general.changeCount` on a utility queue so the UI
/// thread is never blocked. Content is read off-main and only the resulting
/// Sendable snapshot is handed to the main actor.
final class ClipboardMonitor: @unchecked Sendable {
    private let queue = DispatchQueue(
        label: "com.melissasoft.copyninja.clipboard-monitor",
        qos: .utility
    )
    private var timer: DispatchSourceTimer?
    private var lastChangeCount: Int

    private let lock = NSLock()
    private var suppressPending = false

    private let onCapture: @MainActor (ClipboardCapture) -> Void

    init(onCapture: @escaping @MainActor (ClipboardCapture) -> Void) {
        self.onCapture = onCapture
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start(interval: TimeInterval = 0.5) {
        stop()
        let timer = DispatchSource.makeTimerSource(queue: queue)
        timer.schedule(deadline: .now() + interval, repeating: interval)
        timer.setEventHandler { [weak self] in
            self?.poll()
        }
        timer.resume()
        self.timer = timer
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    /// Call before CopyNinja itself writes to the clipboard so its own write
    /// is not re-collected (the store already promotes the entry).
    func suppressNextChange() {
        lock.lock()
        suppressPending = true
        lock.unlock()
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        lock.lock()
        let suppressed = suppressPending
        suppressPending = false
        lock.unlock()
        if suppressed { return }

        guard let capture = ClipboardReader.read(from: pasteboard),
              let processed = ImageProcessor.prepare(capture) else { return }
        Task { @MainActor [onCapture] in
            onCapture(processed)
        }
    }
}
